#!/usr/bin/env python
import os,sys
from eft_calculator import EFT_calculator
from mol2mol import GAMESS_Settings, WriteINP, WritePDB
#  The coordinate structure of intermediate data is:
#      [[elem, x, y, z],
#       [elem, x, y, z],
#       ...]
ele = "OHHOHH"
GAMESS_Settings="""! Gamess input file generated by mol2mol.
 $CONTRL SCFTYP=RHF RUNTYP=GRADIENT MPLEVL=2 $END
 $SYSTEM MWORDS=500 MEMDDI=500 $END
-$CONTRL EXETYP=CHECK $END
 $CONTRL MAXIT=200 $END
-$STATPT OPTTOL=1.0E-5 $END
-$STATPT NSTEP=300 $END
-$DFT NTHE=36 NPHI=72 $END
 $SCF DIRSCF=.T. $END
 $BASIS GBASIS=N311 NGAUSS=6 NDFUNC=2 NPFUNC=2 DIFFSP=.T. DIFFS=.T. $END
 $GUESS GUESS=HUCKEL $END
 $DATA
--Cartesian coordinates with C1 symmetry as follows:
C1
"""

calculator = EFT_calculator()
calculator.setup()
# Please change the following code to whatever needed to generate the input 
# coordinates files
# Please make sure to carry the id number along with the results

def mol2mol_init(ele):
    mol = [[i,0.0,0.0,0.0] for i in ele]
    return mol
size = 200
for id, coors in calculator.gen_atomic_coors(): 
    #print id, coors
    if id%size == 0:
        folder = "EFT_%04d"%(id)
        os.mkdir(folder)
    mol = mol2mol_init(ele)
    for i in range(len(coors)):
        for j in range(3):
            mol[i][j+1]=coors[i][j]
    inf = open("%s/eft.%08d.inp"%(folder,id),"w")
    WriteINP(inf, mol)
    inf.close()

